### ISSUE TITLE
posible bug 

### ISSUE THREAD

**Issue by 10vivar** [Coinffeine/coinffeine#248]
he dejado una orden de venta por debajo de precio de mercado y no se ejecuta .
a que puede deberse?
![bugorder](https://cloud.githubusercontent.com/assets/10363445/5825741/f3858550-a0ed-11e4-9a3e-1badfb5d56ef.png)

**Comment by sortega** [comment]
Buenas,

Parece que se cortan porque son precios sin contar las fees de bitcoin y
del payment processor como se explica en la wiki:
https://github.com/Coinffeine/coinffeine/wiki/Order-amounts

Estamos pensando la mejor forma de evitar ese efecto en el gráfico y,
próximamente pondremos información sobre el precio de corte en la ventana
para abrir órdenes.

Chao

On Tue, Jan 20, 2015 at 9:48 PM, 10vivar <notifications@github.com> wrote:

> he dejado una orden de venta por debajo de precio de mercado y no se
> ejecuta .
> a que puede deberse?
> [image: bugorder]
> <https://cloud.githubusercontent.com/assets/10363445/5825741/f3858550-a0ed-11e4-9a3e-1badfb5d56ef.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Coinffeine/coinffeine/issues/248>.
>



-- 
Sebastián Ortega
Coinffeine Cofounder - http://www.coinffeine.com
