### ISSUE TITLE
Compiling coinffeine 0.4

### ISSUE THREAD

**Issue by juvalen** [Coinffeine/coinffeine#249]
Today February 5th 2015 I downloaded coinffeine-master.zip from GitHub.

I tried to compile it:
$ sbt compile test
...
[warn] Here are some of the libraries that were evicted:
[warn] 	* com.google.guava:guava:12.0 -> 16.0.1
...
[warn] 	* io.netty:netty:3.8.0.Final -> 3.9.2.Final
[warn] Run 'evicted' to see detailed eviction warnings
...
[warn] No main class detected
...
[info] Passed: Total 82, Failed 0, Errors 0, Passed 82
...
[error] Failed: Total 343, Failed 2, Errors 0, Passed 341, Canceled 1
...
[info] Passed: Total 32, Failed 0, Errors 0, Passed 32
[error] (peer/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 1120 s, completed Feb 5, 2015 11:23:44 AM

But when I come to run it:
$ sbt run
[info] Loading project definition from /home/juan/coinffeine-master/project
[info] Set current project to coinffeine (in build file:/home/juan/coinffeine-master/)
[warn] No main class detected
java.lang.RuntimeException: No main class detected.
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last coinffeine/compile:run for the full output.
[error] (coinffeine/compile:run) No main class detected.
[error] Total time: 1 s, completed Feb 5, 2015 11:24:34 AM

I previously compiled 0.3 without any issues

**Comment by apoloval** [comment]
Juan,

We have no `run` target in root project. You will find instructions on building and running in the `README.md` file located in the root directory. 

That 2 failed tests in your log worries me. Could you please send us the whole output of the command to check it out? 

If you have more problems please contact on info@coinffeine.com. 

Best,

-- �lvaro

El 05/02/2015, a las 11:23, juvalen <notifications@github.com> escribi�:
