### ISSUE TITLE
la orden se detiene cuando se apaga el equipo en mitad de una operacion y no vuelve a reanudar 

### ISSUE THREAD

**Issue by 10vivar** [Coinffeine/coinffeine#250]
es correcto esta forma de operar ?
que consecuencias tiene en los monederos?
![captura de pantalla de 2015-03-03 14 23 19](https://cloud.githubusercontent.com/assets/10363445/6471339/3d2606a4-c1ea-11e4-96c4-d22d423e11f9.png)

**Comment by apoloval** [comment]
Por lo que indica el screenshot, los exchanges se han reanudado. ¿Quieres decir que no avanzan? De ser así, podría deberse a que la contraparte se haya retirado. ¿Puedes adjuntar el fichero `Coinffeine.log` del directorio de datos de la aplicación?

**Comment by 10vivar** [comment]
te lo mando aqui porque en github solo me permite enviar imagenes
saludos

El 4 de marzo de 2015, 9:30, Alvaro Polo <notifications@github.com>
escribió:

> Por lo que indica el screenshot, los exchanges se han reanudado. ¿Quieres
> decir que no avanzan? De ser así, podría deberse a que la contraparte se
> haya retirado. ¿Puedes adjuntar el fichero Coinffeine.log del directorio
> de datos de la aplicación?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Coinffeine/coinffeine/issues/250#issuecomment-77115974>
> .
>



-- 
Bitcoin Adress:

**Comment by apoloval** [comment]
Parece que no se ha llegado a adjuntar nada por correo. ¿Puedes enviarlo a info@coinffeine.com? Gracias.
