### ISSUE TITLE
Dependencies problem at Sonatype Nexus Repository Manager

### ISSUE THREAD

**Issue by naumenkogs** [Coinffeine/coinffeine#258]
I've seen the same problem in resolved issues, but it seems to come back now.

[error] SERVER ERROR: Server Error url=http://repository.coinffeine.com/content/repositories/third-party/no/vedaadata/sbt-javafx_2.10_0.13/0.6.2-coinffeine/sbt-javafx-0.6.2-coinffeine.pom
[error] Unable to find credentials for [Sonatype Nexus Repository Manager @ oss.sonatype.org].

I have a number of errors later about missing dependencies so I cannot use the system.
If you open that URL you will see that third-party folder is empty, but it looks for dependencies there.

**Comment by apoloval** [comment]
SBT is anything but simple. I also has a lot of errors when building the first time. I couldn't investigate in depth but my feeling is that it tries to obtain each artifact from the repositories defined for the project. If one of this repos fails, it tries again with the next until it finds one that works.

I just tried to build from sources using this very repository from a fresh machine. SBT prints a lot of error lines like that, but it finally finds all artifacts in other repositories and the build succeeds.

**Comment by naumenkogs** [comment]
I would not have opened this issue if something were good. That problems makes application to fail while I'm trying to get things to login in system, after redirect to my browser.

**Comment by apoloval** [comment]
Could you please run `sbt compile`, copy the whole output and paste it here?

**Comment by apoloval** [comment]
BTW, I can follow this link without problems.

 http://repository.coinffeine.com/content/repositories/third-party/no/vedaadata/sbt-javafx_2.10_0.13/0.6.2-coinffeine/sbt-javafx-0.6.2-coinffeine.pom

The POM file is shown without any problem. Perhaps there was some transient error in the Nexus server.

**Comment by naumenkogs** [comment]
Seems like someone fixed it in prev 2 days. I'll check whether the whole list of dependencies are fine and probably close the issue.

**Comment by apoloval** [comment]
Last weekend we had some issues with our dev infrastructure. That could affect the Nexus server. 

Many thanks for reporting. And for your patience.

**Comment by naumenkogs** [comment]
Evertything seems fine right now.
